<div id="news">
	<h3>News and Announcements</h3>
	<dl>
		<dt>May 18 2011</dt>
                <dd>2011 NoSQL Now! has select Hypertable for the Conference Program<br>August 23 - 25, <a href="">2011 NoSQL Now! »</a> San Jose, CA</dd>
	</dl>
	<dl>
		<dt>Oct 17 2010</dt>
		<dd>Doug Judd will present <a href="http://www.meetup.com/cloudcomputing/calendar/14362435/">Database Architectures and Hypertable</a> at the Silicon Valley Cloud Computing Group Meetup, October 21st 2010<br> Fenwick & West, Mountain View, CA</dd>
	</dl>

</div><!-- news -->




