<div id="news">
	<h3>News and Announcements</h3>
	<dl>
		<dt>August 1 2011</dt>
                <dd>"Load Balancing in Hypertable" to be presented at <a href="http://osullivan.ucc.ie/aaai-2011-aidc/AIDC_2011_-_AAAI_2011_Workshop_on_AI_for_Data_Centre_Management_and_Cloud_Computing/Welcome.html">AAAI 2011 Workshop - AI For Data Center Management and Cloud Computing »</a><br>August 7, San Francisco, CA</dd>
	</dl>
	<dl>
		<dt>May 18 2011</dt>
                <dd>2011 NoSQL Now! has select Hypertable for the Conference Program<br>August 23 - 25, <a href="http://nosql2011.wilshireconferences.com/">2011 NoSQL Now! »</a> San Jose, CA</dd>
	</dl>

</div><!-- news -->




