<div id="news">
	<h3>News and Announcements</h3>
	<dl>
		<dt>June 17 2011</dt>
                <dd>Hypertable, Inc. is hiring <a href="http://www.hypertable.com/careers/">Core Hypertable Engineers »</a> Positions available in Silicon Valley and Europe</dd>
	</dl>
	<dl>
		<dt>May 18 2011</dt>
                <dd>2011 NoSQL Now! has select Hypertable for the Conference Program<br>August 23 - 25, <a href="http://nosql2011.wilshireconferences.com/">2011 NoSQL Now! »</a> San Jose, CA</dd>
	</dl>

</div><!-- news -->




